# Generated by Django 5.1.6 on 2025-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
